version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.4.1"
    shell: /bin/bash --login -eo pipefail

    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - run: sudo gem install bundler
      - run: bundle install --path vendor/bundle
      - run:
          name: Build and run tests
          command: bundle exec fastlane scan
          environment:
            SCAN_DEVICE: iPhone 6
            LC_ALL: en_US.UTF-8
            LANG: en_US.UTF-8
            SCAN_SCHEME: todoly
            platform: iOS Simulator

      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: /tmp/test-results
          destination: scan-test-results
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
          
  adhoc:
    macos:
      xcode: "9.4.1"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output


workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
      - adhoc
